# -*- coding: utf-8 -*-
"""Lista

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbv78ftCSfcufr1GdxpDyM2UKXPzA2F6

Exercício 1
"""

numero = 1
while numero <= 10:
     print(numero)
     numero+= 1

"""Exercício 2"""

soma = 0
numero = int(input("Digite um número (0 para parar): "))

while numero != 0:
  soma += numero
  numero = int(input("Digite outro numero (0 para parar): "))
print("A soma é:", soma)

"""Exercício 3

"""

numero = int(input("Digite um número: "))
contador = 1

while contador <= 10:
  print(numero, "x", contador, "=", numero * contador)
  contador += 1

"""Exercício 4"""

for numero in range(10, 0, -1):
  print(numero)

"""Exercício 5

"""

for numero in range (2, 21, 2):
  print (numero)

"""Exercício 6"""

nomes = ["Aaron", "Jhonny", "Max", "Potter", "Lucien"]
for nome in nomes:
  print(nome)

"""Exercício 7

"""

numero =  int(input("Digite um número: "))
fatorial = 1

for i in range (1, numero + 1):
  fatorial *= i

print("O fatorial é:", fatorial)